import type { Metadata } from 'next'
// import { Poppins } from 'next/font/google'
import './globals.css'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import Providers from './Providers'

// const poppins = Poppins({
//     weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
//     subsets: ['latin'],
//     display: 'swap',
// })

// const fira = Fira_Code({
//     weight: ['300', '400', '500', '600', '700'],
//     subsets: ['latin'],
//     display: 'swap',
// })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    {children}
                    <ToastContainer />
                </Providers>
            </body>
        </html>
    )
}
